//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Fan
{
	public virtual object int speed
	{
		get;
		set;
	}

	public virtual object bool on
	{
		get;
		set;
	}

	public virtual object double radius
	{
		get;
		set;
	}

	public virtual object Attribute1
	{
		get;
		set;
	}

	public virtual void getSpeed()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getOn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setSpeed()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setOn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getRadius()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setRadius()
	{
		throw new System.NotImplementedException();
	}

}

